language: python

services:
  - docker

before_install:
  - docker-compose up --detach

script:
  - docker exec server celery -A celeryEmails worker -l info
  - docker exec server python manage.py test