version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: server
    image: celeryemails
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on: 
      - redis
  
  celery:
    build: .
    command: celery -A celeryEmails worker -l info
    container_name: celeryLogs
    volumes:
      - .:/code
    depends_on: 
      - redis 

# Run this command after docker-compose up:
# docker exec -it server celery -A celeryEmails worker -l info