version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: server
    image: celeryemails
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on: 
      - redis
 